const JOKES: string[] = [
  "You're not stuck in traffic, you ARE traffic. Now smile about it.",
  "If you were a vegetable, you'd be a cute-cumber.",
  "Plot twist: the fridge light does go off when you close the door.",
  "Fun fact: your bed misses you too.",
  "Somewhere, a dog is dreaming about you right now.",
  "Your hair looks amazing today and I'm not just saying that.",
  "You've survived 100% of your bad days. That's a perfect record.",
  "A burrito is just a sleeping bag for rice.",
  "If Monday had a face, even it would apologize to you.",
  "Remember: you're someone's reason to smile. Probably a dentist.",
  "Life tip: you can't be sad while holding a puppy. It's science.",
  "Breaking news: local legend caught looking incredible on camera.",
  "Today's forecast: 100% chance of you being awesome.",
  "Why did the scarecrow win an award? Because he was outstanding in his field — like you.",
  "Your future self just sent a thank-you note. Keep going.",
  "Coffee loves you back. That's at least one healthy relationship.",
  "You're the WiFi signal everyone wants to be close to.",
  "Parallel universe you is jealous of this universe you.",
  "Plot twist: everything works out.",
  "Smile! Your face is doing that thing where it forgets how great it is.",
  "If you were a cat, you'd have nine reasons to be happy right now.",
  "You're proof that good things come in legendary packages.",
  "Somewhere out there, a pizza is being made for you.",
  "The world is 70% water. You're basically a cucumber at a spa.",
  "Your smile could crash a server. Too much data to handle.",
  "Today is brought to you by the letter U, because U are amazing.",
  "Even autocorrect can't fix how perfect you are.",
  "You're like a four-leaf clover — hard to find and lucky to have.",
  "If happiness were a currency, you'd make everyone rich.",
  "A wise person once said: just eat the cake.",
  "Your vibe attracts your tribe. And your tribe has great taste.",
  "Knock knock. Who's there? The best version of you. Let them in.",
  "You're not procrastinating, you're on energy-saving mode.",
  "In a room full of art, I'd still look at you.",
  "Your ex's loss is literally everyone else's gain.",
  "You don't need a filter. Reality looks good on you.",
  "Cheese doesn't ask silly questions. Cheese understands. Be like cheese.",
  "When nothing goes right, go left. Then take a selfie.",
  "Studies show that 10 out of 10 mirrors agree: you look great.",
  "If plan A didn't work, the alphabet has 25 more letters.",
  "You're one good nap away from a great mood.",
  "Breaking: scientists confirm you're doing better than you think.",
  "Fun fact: sharks are afraid of you. Probably.",
  "You're not weird, you're a limited edition.",
  "The sun is jealous of how bright you are.",
  "Your socks might not match but your energy is immaculate.",
  "If you were a song, you'd be on everyone's playlist.",
  "Plot twist: the hokey pokey really IS what it's all about.",
  "Congrats on being alive today. The odds were astronomical.",
  "Remember: even a 404 page gets visited sometimes. You're way above that.",
  "You have the emotional range of a fine wine. Complex and worth it.",
  "A penguin somewhere just fell over. Feel better?",
  "The stars aligned for you. They just forgot to send the memo.",
  "You're like a software update — everyone's better off after meeting you.",
  "Hot take: you deserve that second cookie.",
  "Your ancestors didn't survive all that history for you to be sad on camera.",
  "If life gives you lemons, add vodka. Wait — smile first, then vodka.",
  "You're the human equivalent of a perfectly toasted marshmallow.",
  "Fact: nobody in the history of calming down has calmed down by being told to calm down. So here's a joke instead.",
  "Even your shadow wants to be around you. Literally follows you everywhere.",
  "The odds of you existing are 1 in 400 trillion. You're basically a miracle with a face.",
  "Roses are red, violets are blue, this camera's lucky it gets to see you.",
  "Friendly reminder: naps are just horizontal life pauses.",
  "Be the reason someone Googles 'is it possible to be that cool?'",
  "If you were a spice, you'd be flour. Because you're all-purpose amazing.",
  "The ocean called. It wants its waves back because yours are better.",
  "Your DNA literally said 'let's make something incredible' and here you are.",
  "A taco never judges you. Channel your inner taco.",
  "Don't worry about the world ending today. It's already tomorrow in Australia.",
  "You are the avocado on the toast of life. Extra. But necessary.",
  "Math class taught me one thing: problems always have solutions. Also, you're a 10.",
  "Somewhere, someone just thought of you and smiled.",
  "Life is short. Smile while you still have teeth.",
  "You're giving main character energy right now.",
  "If you were a candle, you'd be the expensive kind that smells really good.",
  "Your potential is so high it needs its own ZIP code.",
  "Quick reminder: you've already made it through every single tough day so far.",
  "You know what's beautiful? Read the first word again.",
  "Even Mondays are afraid of your energy.",
  "You're not behind in life. Netflix just loaded your next episode.",
  "Siri, show me someone amazing. Oh wait, the camera's already on.",
  "Your smile is like a reset button for bad vibes.",
  "If kindness was a sport, you'd be in the hall of fame.",
  "Remember: diamonds started as coal that handled stress exceptionally well.",
  "The WiFi might be slow but you? You're always connected to greatness.",
  "A group of flamingos is called a flamboyance. You'd fit right in.",
  "You're not old, you're vintage. And vintage is premium.",
  "Somewhere in the multiverse, you're a superhero. Honestly, probably in this one too.",
  "If you were a browser tab, you'd be the one people are afraid to close.",
  "Just remember: stressed is just desserts spelled backwards.",
  "Your face just made this camera's entire week.",
  "Quick poll: are you always this radiant or is it just today?",
  "You + this moment = literally unbeatable.",
  "Even gravity can't bring you down. Well, physically it can, but spiritually? Never.",
  "You're like a shooting star: rare, stunning, and impossible to ignore.",
  "Today's score: You: 1, Bad Mood: 0.",
  "Not all heroes wear capes. Some just open their camera and look incredible.",
  "The awkward moment when you're so awesome, even sadness gets confused.",
  "If confidence had a face, it would look suspiciously like yours.",
  "You've been promoted from sad to mildly amused. Congratulations.",
];

export function getRandomJoke(): string {
  return JOKES[Math.floor(Math.random() * JOKES.length)];
}

export function getRandomJokeExcluding(last: string): string {
  if (JOKES.length <= 1) return JOKES[0];
  let joke: string;
  do {
    joke = JOKES[Math.floor(Math.random() * JOKES.length)];
  } while (joke === last);
  return joke;
}
